let T = [17, 38, 10, 25, 72]
console.log(T.sort())
T.push(12)
console.log(T)
console.log(T.reverse())
console.log(T.indexOf(17))
T.splice(T.indexOf(38),1)
console.log(T)
console.log(T.slice(1,3))
console.log(T.slice(0,2))
console.log(T.slice(2,T.length))
